In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.formula.api import ols
import statsmodels.api as sm

In [2]:
#para bajar un archivo del secretariad lo primero es guargarlos como cvs delimitado por comas y codificado en UTF-8

In [3]:
delitos_estatales_con_acentos=pd.read_csv("delito_estatal_2015_2020.csv", delimiter="," , encoding='utf-8')
delitos_estatales_con_acentos.head()

,Ao,Clave_Ent,Entidad,Bien_juridico_afectado,Tipo_de_delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3.0,0.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0.0,0.0,2.0,2.0,3.0,2.0,0.0,1.0,2.0,0.0,0.0,0.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# después tenemos el problema de los acentos que hay que eliminar con replace

In [5]:
buscar=("Michoac·n de Ocampo", "Nuevo LeÛn", "QuerÈtaro", "San Luis PotosÌ", "Veracruz de Ignacio de la Llave", "Yucat·n", "ExtorsiÛn","FalsificaciÛn", "Otros delitos del Fuero Com˙n", "Otros bienes jurÌdicos afectados (del fuero com˙n)", "EvasiÛn de presos", "Tr·fico de menores", "ViolaciÛn simple", "ViolaciÛn equiparada", "DaÒo a la propiedad", "Robo a casa habitaciÛn", "Robo de vehÌculo automotor", "Robo a transe˙nte en vÌa p˙blica", "Robo a transe˙nte en espacio abierto al p˙blico", "Robo en transporte p˙blico individual", "Robo en transporte p˙blico colectivo", "Robo a instituciÛn bancaria", "Violencia de gÈnero en todas sus modalidades distinta a la violencia familiar", "En accidente de tr·nsito", "Secuestro para causar daÒo","Secuestro exprÈs", "Robo de embarcaciones pequeÒas y grandes Con violencia", "Robo de embarcaciones pequeÒas y grandes Sin violencia","NaN" )

In [6]:
reemplazar_por=("Michoacan de Ocampo", "Nuevo Leon", "Queretaro", "San Luis Potosi", "Veracruz", "Yucatan", "Extorsion","Falsificacion", "Otros delitos del Fuero Comun", "Otros bienes juridicos afectados (del fuero comun)", "Evasion de presos", "Trafico de menores", "Violacion simple", "Violacion equiparada", "Dano a la propiedad", "Robo a casa habitacion", "Robo de vehiculo automotor", "Robo a transeunte en via publica", "Robo a transeunte en espacio abierto al publico", "Robo en transporte publico individual", "Robo en transporte publico colectivo", "Robo a institucion bancaria", "Violencia de genero en todas sus modalidades distinta a la violencia familiar", "En accidente de transito", "Secuestro para causar dano", "Secuestro expres", "Robo de embarcaciones pequenas y grandes Con violencia", "Robo de embarcaciones pequenas y grandes Sin violencia",0)

In [7]:

delitos_estatales = delitos_estatales_con_acentos.replace(buscar, reemplazar_por)

In [8]:

delitos_estatales.tail()

,Ao,Clave_Ent,Entidad,Bien_juridico_afectado,Tipo_de_delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
18811,2020,32,Zacatecas,Otros bienes juridicos afectados (del fuero co...,Falsificacion,Falsificacion,Falsificacion,11.0,12.0,5.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18812,2020,32,Zacatecas,Otros bienes juridicos afectados (del fuero co...,Contra el medio ambiente,Contra el medio ambiente,Contra el medio ambiente,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18813,2020,32,Zacatecas,Otros bienes juridicos afectados (del fuero co...,Delitos cometidos por servidores p˙blicos,Delitos cometidos por servidores p˙blicos,Delitos cometidos por servidores p˙blicos,20.0,20.0,28.0,13.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18814,2020,32,Zacatecas,Otros bienes juridicos afectados (del fuero co...,Electorales,Electorales,Electorales,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18815,2020,32,Zacatecas,Otros bienes juridicos afectados (del fuero co...,Otros delitos del Fuero Comun,Otros delitos del Fuero Comun,Otros delitos del Fuero Comun,197.0,182.0,168.0,133.0,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df = delitos_estatales

In [15]:
df['Total']=d_e.iloc[:,7:19].sum(axis=1)

In [16]:
df.head()

,Ao,Clave_Ent,Entidad,Bien_juridico_afectado,Tipo_de_delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Total
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3.0,0.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,18.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0.0,0.0,2.0,2.0,3.0,2.0,0.0,1.0,2.0,0.0,0.0,0.0,12.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [17]:
df.shape

(18816, 20)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18816 entries, 0 to 18815
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Ao                      18816 non-null  int64
 1   Clave_Ent               18816 non-null  int64
 2   Entidad                 18816 non-null  object
 3   Bien_juridico_afectado  18816 non-null  object
 4   Tipo_de_delito          18816 non-null  object
 5   Subtipo de delito       18816 non-null  object
 6   Modalidad               18816 non-null  object
 7   Enero                   18816 non-null  float64
 8   Febrero                 18816 non-null  float64
 9   Marzo                   18816 non-null  float64
 10  Abril                   18816 non-null  float64
 11  Mayo                    18816 non-null  float64
 12  Junio                   15680 non-null  float64
 13  Julio                   15680 non-null  float64
 14  Agosto                  15680 non-null  float64
 15  Septiembre              15680 non-null  float64
 16  Octubre                 15680 non-null  float64
 17  Noviembre               15680 non-null  float64
 18  Diciembre               15680 non-null  float64
 19  Total                   18816 non-null  float64
dtypes: float64(13), int64(2), object(5)
memory usage: 2.9+ MB

In [19]:
df.describe()

,Ao,Clave_Ent,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Total
count,18816.000000,18816.000000,18816.000000,18816.000000,18816.000000,18816.000000,18816.000000,15680.000000,15680.000000,15680.000000,15680.000000,15680.000000,15680.000000,15680.000000,18816.000000
mean,2017.500000,16.500000,46.436597,46.401201,50.033429,46.421928,49.033270,50.071492,49.538265,50.860013,49.177487,51.812564,48.241327,46.306952,526.666507
std,1.707871,9.233338,168.993828,169.729485,184.266393,172.461867,184.431925,186.459065,187.154863,190.695953,185.090921,196.595850,179.974937,176.414449,1992.330210
min,2015.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2016.000000,8.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2017.500000,16.500000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,18.000000
75%,2019.000000,24.250000,22.000000,23.000000,25.000000,22.000000,23.000000,24.000000,23.000000,25.000000,23.000000,25.000000,23.000000,21.000000,252.000000
max,2020.000000,32.000000,5954.000000,6114.000000,6677.000000,5941.000000,6978.000000,6427.000000,5879.000000,6096.000000,5917.000000,6276.000000,5470.000000,6190.000000,70179.000000

In [20]:
df.isnull().sum()

Ao                           0
Clave_Ent                    0
Entidad                      0
Bien_juridico_afectado       0
Tipo_de_delito               0
Subtipo de delito            0
Modalidad                    0
Enero                        0
Febrero                      0
Marzo                        0
Abril                        0
Mayo                         0
Junio                     3136
Julio                     3136
Agosto                    3136
Septiembre                3136
Octubre                   3136
Noviembre                 3136
Diciembre                 3136
Total                        0
dtype: int64

In [25]:
df.groupby(['Entidad']).get_group('Aguascalientes') # Muestra los registros de Aguascalientes

,Ao,Clave_Ent,Entidad,Bien_juridico_afectado,Tipo_de_delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Total
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3.0,0.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,18.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0.0,0.0,2.0,2.0,3.0,2.0,0.0,1.0,2.0,0.0,0.0,0.0,12.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15773,2020,1,Aguascalientes,Otros bienes juridicos afectados (del fuero co...,Falsificacion,Falsificacion,Falsificacion,83.0,85.0,65.0,52.0,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347.0
15774,2020,1,Aguascalientes,Otros bienes juridicos afectados (del fuero co...,Contra el medio ambiente,Contra el medio ambiente,Contra el medio ambiente,0.0,2.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
15775,2020,1,Aguascalientes,Otros bienes juridicos afectados (del fuero co...,Delitos cometidos por servidores p˙blicos,Delitos cometidos por servidores p˙blicos,Delitos cometidos por servidores p˙blicos,34.0,34.0,38.0,32.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159.0
15776,2020,1,Aguascalientes,Otros bienes juridicos afectados (del fuero co...,Electorales,Electorales,Electorales,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
15777,2020,1,Aguascalientes,Otros bienes juridicos afectados (del fuero co...,Otros delitos del Fuero Comun,Otros delitos del Fuero Comun,Otros delitos del Fuero Comun,112.0,99.0,100.0,64.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,444.0

In [36]:
df.groupby(['Tipo_de_delito']).get_group('Homicidio').describe()

,Ao,Clave_Ent,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Total
count,1728.00000,1728.000000,1728.000000,1728.000000,1728.000000,1728.000000,1728.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1728.000000
mean,2017.50000,16.500000,11.103588,10.748843,11.742477,11.327546,11.940972,11.186111,11.515972,11.663889,11.451389,11.576389,11.499306,12.147917,124.397569
std,1.70832,9.235765,22.402881,21.209696,23.222226,22.683500,23.709519,22.073447,22.603597,22.630600,22.369607,23.164961,22.934023,24.063668,245.799274
min,2015.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2016.00000,8.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2017.50000,16.500000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,19.000000
75%,2019.00000,24.250000,12.000000,12.000000,13.000000,12.000000,13.000000,13.000000,13.000000,13.000000,13.000000,12.000000,12.000000,13.000000,139.000000
max,2020.00000,32.000000,256.000000,218.000000,211.000000,221.000000,245.000000,176.000000,200.000000,194.000000,221.000000,194.000000,209.000000,196.000000,2261.000000